export const adminOlympiadCopy = {
    rus: {
        testingAdmin: 'Админка тестирования',
        backToOlympiads: 'Назад к олимпиадам',
        olympiadNotFound: 'Олимпиада не найдена.',
        overview: 'Обзор',
        participants: 'Участники',
        results: 'Результаты',
        stageTwo: 'Этап 2',
        settings: 'Настройки олимпиады',
        olympiadTitle: 'Название олимпиады',
        description: 'Описание',
        registrationOpen: 'Регистрация открыта',
        olympiadActive: 'Олимпиада активна',
        defaultQuestionCount: 'Вопросов 1 этапа по умолчанию',
        defaultQuestionHelp: 'Это значение будет подставляться в новые предметы.',
        passPercent: 'Порог прохождения 1 этапа, %',
        startsAt: 'Дата начала',
        endsAt: 'Дата окончания',
        saveOlympiad: 'Сохранить олимпиаду',
        olympiadSaved: 'Настройки олимпиады сохранены.',
        statsParticipants: 'Участников',
        statsSubjects: 'Предметов',
        statsReadySubjects: 'Готовых предметов',
        statsEliminated: 'Выбыли',
        statsStageTwo: 'Допущены ко 2 этапу',
        statsCompleted: 'Завершили 2 этап',
        subjects: 'Предметы',
        subjectName: 'Название предмета',
        addSubject: 'Добавить предмет',
        subjectCreated: 'Предмет добавлен.',
        subjectSaved: 'Параметры предмета сохранены.',
        archiveSubject: 'Архивировать предмет',
        archiveSubjectConfirm: 'Архивировать предмет? Он исчезнет из списка.',
        subjectArchived: 'Предмет архивирован.',
        assignedUser: 'Назначен',
        assignUser: 'Назначить пользователя',
        selectUser: 'Выберите пользователя',
        noAssignedUser: 'Не назначен',
        noCurators: 'Нет пользователей с ролью составителя.',
        questionCountLabel: 'Количество вопросов 1 этапа',
        questionCountHelp: 'Сколько случайных вопросов получит студент',
        uploadedQuestions: 'Всего загружено вопросов',
        saveSubject: 'Сохранить предмет',
        ready: 'Готов',
        notReady: 'Не готов',
        missingCurator: 'Не назначен составитель',
        missingQuestions: 'Недостаточно вопросов',
        filters: 'Фильтры',
        searchPlaceholder: 'Поиск по ФИО, e-mail, телефону, школе, городу',
        language: 'Язык',
        profile: 'Профиль',
        status: 'Статус',
        all: 'Все',
        exportCsv: 'Экспорт CSV',
        participantName: 'ФИО',
        email: 'E-mail',
        phone: 'Телефон',
        location: 'Регион / город',
        school: 'Школа',
        registeredAt: 'Дата регистрации',
        overallScore: 'Общий балл',
        stage1Passed: 'Пройдено предметов 1 этапа',
        participantCount: 'Найдено участников',
        noParticipants: 'Участников пока нет.',
        noSubjects: 'Предметы еще не добавлены.',
        noResults: 'Результатов пока нет.',
        noStageTwo: 'Нет участников для 2 этапа.',
        saveStageTwo: 'Сохранить этап 2',
        stageTwoSaved: 'Данные 2 этапа сохранены.',
        meetingLink: 'Ссылка на Zoom/Meet',
        stageTwoStatus: 'Статус 2 этапа',
        stageTwoScore: 'Балл 2 этапа, %',
        subject: 'Предмет',
        stageOne: '1 этап',
        total: 'Итог',
        invalidSubjectName: 'Введите название предмета.',
        invalidQuestionCount: 'Введите количество вопросов от 1 до 100.',
        invalidOlympiadTitle: 'Введите название олимпиады.',
        invalidPassPercent: 'Введите порог прохождения от 1 до 100.',
        stageTwoScoreRequired: 'Для завершенного 2 этапа укажите балл.',
        stageTwoScoreInvalid: 'Балл 2 этапа должен быть от 0 до 100.',
        exportedParticipants: 'Список участников выгружен.',
        exportedResults: 'Результаты выгружены.',
        exportedStageTwo: 'Список 2 этапа выгружен.',
    },
    kaz: {
        testingAdmin: 'Тестілеу әкімшілігі',
        backToOlympiads: 'Олимпиадаларға оралу',
        olympiadNotFound: 'Олимпиада табылмады.',
        overview: 'Шолу',
        participants: 'Қатысушылар',
        results: 'Нәтижелер',
        stageTwo: '2-кезең',
        settings: 'Олимпиада баптаулары',
        olympiadTitle: 'Олимпиада атауы',
        description: 'Сипаттама',
        registrationOpen: 'Тіркелу ашық',
        olympiadActive: 'Олимпиада белсенді',
        defaultQuestionCount: '1-кезең сұрақтарының әдепкі саны',
        defaultQuestionHelp: 'Бұл мән жаңа пәндерге автоматты қойылады.',
        passPercent: '1-кезеңнен өту шегі, %',
        startsAt: 'Басталу күні',
        endsAt: 'Аяқталу күні',
        saveOlympiad: 'Олимпиаданы сақтау',
        olympiadSaved: 'Олимпиада баптаулары сақталды.',
        statsParticipants: 'Қатысушылар',
        statsSubjects: 'Пәндер',
        statsReadySubjects: 'Дайын пәндер',
        statsEliminated: 'Шығып қалғандар',
        statsStageTwo: '2-кезеңге өткендер',
        statsCompleted: '2-кезеңді аяқтағандар',
        subjects: 'Пәндер',
        subjectName: 'Пән атауы',
        addSubject: 'Пән қосу',
        subjectCreated: 'Пән қосылды.',
        subjectSaved: 'Пән параметрлері сақталды.',
        archiveSubject: 'Пәнді архивтеу',
        archiveSubjectConfirm: 'Пәнді архивтеу керек пе? Ол тізімнен жоғалады.',
        subjectArchived: 'Пән архивтелді.',
        assignedUser: 'Бекітілген',
        assignUser: 'Пайдаланушыны бекіту',
        selectUser: 'Пайдаланушыны таңдаңыз',
        noAssignedUser: 'Бекітілмеген',
        noCurators: 'Құрастырушы рөлі бар пайдаланушылар жоқ.',
        questionCountLabel: '1-кезеңдегі сұрақ саны',
        questionCountHelp: 'Студентке кездейсоқ шығатын сұрақ саны',
        uploadedQuestions: 'Жүктелген сұрақтар саны',
        saveSubject: 'Пәнді сақтау',
        ready: 'Дайын',
        notReady: 'Дайын емес',
        missingCurator: 'Құрастырушы тағайындалмаған',
        missingQuestions: 'Сұрақтар жеткіліксіз',
        filters: 'Сүзгілер',
        searchPlaceholder: 'Аты-жөні, e-mail, телефон, мектеп, қала бойынша іздеу',
        language: 'Тіл',
        profile: 'Бейін',
        status: 'Мәртебе',
        all: 'Барлығы',
        exportCsv: 'CSV экспорт',
        participantName: 'Аты-жөні',
        email: 'E-mail',
        phone: 'Телефон',
        location: 'Өңір / қала',
        school: 'Мектеп',
        registeredAt: 'Тіркелген күні',
        overallScore: 'Жалпы балл',
        stage1Passed: '1-кезеңнен өткен пәндер',
        participantCount: 'Табылған қатысушылар',
        noParticipants: 'Қатысушылар әлі жоқ.',
        noSubjects: 'Пәндер әлі қосылмаған.',
        noResults: 'Нәтижелер әлі жоқ.',
        noStageTwo: '2-кезеңге қатысушылар жоқ.',
        saveStageTwo: '2-кезеңді сақтау',
        stageTwoSaved: '2-кезең деректері сақталды.',
        meetingLink: 'Zoom/Meet сілтемесі',
        stageTwoStatus: '2-кезең мәртебесі',
        stageTwoScore: '2-кезең балы, %',
        subject: 'Пән',
        stageOne: '1-кезең',
        total: 'Қорытынды',
        invalidSubjectName: 'Пән атауын енгізіңіз.',
        invalidQuestionCount: '1 мен 100 аралығындағы сұрақ санын енгізіңіз.',
        invalidOlympiadTitle: 'Олимпиада атауын енгізіңіз.',
        invalidPassPercent: 'Өту шегін 1 мен 100 аралығында енгізіңіз.',
        stageTwoScoreRequired: 'Аяқталған 2-кезең үшін балл енгізіңіз.',
        stageTwoScoreInvalid: '2-кезең балы 0 мен 100 аралығында болуы керек.',
        exportedParticipants: 'Қатысушылар тізімі экспортталды.',
        exportedResults: 'Нәтижелер экспортталды.',
        exportedStageTwo: '2-кезең тізімі экспортталды.',
    },
};
