export function buildEmptyOptions() {
    return [
        { text: '', is_correct: true },
        { text: '', is_correct: false },
        { text: '', is_correct: false },
        { text: '', is_correct: false },
        { text: '', is_correct: false },
    ];
}

export function buildEmptyQuestionForm() {
    return {
        text: '',
        explanation: '',
        options: buildEmptyOptions(),
    };
}

export const curatorCopy = {
    rus: {
        subtitle: 'Выберите назначенный предмет.',
        assignedSubjects: 'Мои предметы',
        noAssignedSubjects: 'Вам еще не назначили предметы.',
        questionsList: 'Список вопросов',
        noQuestions: 'По этому предмету вопросов пока нет.',
        explanation: 'Пояснение',
        answerOptions: 'Варианты ответа',
        editQuestion: 'Редактировать',
        saveQuestion: 'Сохранить вопрос',
        saveAndCreateAnother: 'Сохранить и создать новый',
        cancelEdit: 'Отмена',
        deleteQuestion: 'Удалить',
        deleteQuestionConfirm: 'Удалить этот вопрос?',
        questionCreated: 'Вопрос добавлен.',
        questionUpdated: 'Вопрос обновлен.',
        questionDeleted: 'Вопрос удален.',
        subjectQuestions: 'Вопросы по предмету',
        olympiadLabel: 'Олимпиада',
        assignedQuestionCount: 'Вопросов',
        openSubject: 'Открыть предмет',
        backToSubjects: 'К предметам',
        createQuestion: 'Создать вопрос',
        editQuestionTitle: 'Редактирование вопроса',
        createQuestionTitle: 'Новый вопрос',
        answers: 'Ответы',
        correctAnswer: 'Правильный',
        actions: 'Действия',
        question: 'Вопрос',
        subjectNotFound: 'Предмет не найден или не назначен вам.',
        questionNotFound: 'Вопрос не найден.',
        formattingHelp: 'Можно вставлять изображения, таблицы и блоки кода с сохранением отступов.',
        preview: 'Предпросмотр',
    },
    kaz: {
        subtitle: 'Бекітілген пәнді таңдаңыз.',
        assignedSubjects: 'Менің пәндерім',
        noAssignedSubjects: 'Сізге әлі пән бекітілмеген.',
        questionsList: 'Сұрақтар тізімі',
        noQuestions: 'Бұл пән бойынша әзірге сұрақ жоқ.',
        explanation: 'Түсіндірме',
        answerOptions: 'Жауап нұсқалары',
        editQuestion: 'Өңдеу',
        saveQuestion: 'Сұрақты сақтау',
        saveAndCreateAnother: 'Сақтап, жаңасын қосу',
        cancelEdit: 'Болдырмау',
        deleteQuestion: 'Өшіру',
        deleteQuestionConfirm: 'Осы сұрақты өшіру керек пе?',
        questionCreated: 'Сұрақ қосылды.',
        questionUpdated: 'Сұрақ жаңартылды.',
        questionDeleted: 'Сұрақ өшірілді.',
        subjectQuestions: 'Пән бойынша сұрақтар',
        olympiadLabel: 'Олимпиада',
        assignedQuestionCount: 'Сұрақ саны',
        openSubject: 'Пәнді ашу',
        backToSubjects: 'Пәндерге оралу',
        createQuestion: 'Сұрақ қосу',
        editQuestionTitle: 'Сұрақты өңдеу',
        createQuestionTitle: 'Жаңа сұрақ',
        answers: 'Жауаптар',
        correctAnswer: 'Дұрыс',
        actions: 'Әрекеттер',
        question: 'Сұрақ',
        subjectNotFound: 'Пән табылмады немесе сізге бекітілмеген.',
        questionNotFound: 'Сұрақ табылмады.',
        formattingHelp: 'Сурет, кесте және шегінісі сақталатын код блоктарын енгізуге болады.',
        preview: 'Алдын ала қарау',
    },
};
