export const adminCopy = {
    rus: {
        title: 'Панель администратора',
        olympiadTitle: 'Название олимпиады',
        createOlympiad: 'Создать олимпиаду',
        openOlympiad: 'Управлять тестированием',
        registeredCount: 'Зарегистрировались',
        registrationStatus: 'Регистрация',
        subjectName: 'Название предмета',
        addSubject: 'Добавить предмет',
        subjects: 'Предметы',
        noOlympiads: 'Олимпиад пока нет.',
        noSubjects: 'Предметы еще не добавлены.',
        assignUser: 'Назначить пользователя',
        selectUser: 'Выберите пользователя',
        saveUser: 'Сохранить',
        assignedUser: 'Назначен',
        noAssignedUser: 'Не назначен',
        noCurators: 'Нет пользователей с ролью составителя.',
        olympiadCreated: 'Олимпиада создана.',
        subjectCreated: 'Предмет добавлен.',
        userAssigned: 'Пользователь назначен на предмет.',
        registrationUpdated: 'Статус регистрации обновлен.',
        archiveOlympiad: 'Архивировать',
        archiveOlympiadConfirm: 'Архивировать олимпиаду? Она исчезнет из списка.',
        olympiadArchived: 'Олимпиада архивирована.',
        testingAdmin: 'Админка тестирования',
        backToOlympiads: 'Назад к олимпиадам',
        olympiadNotFound: 'Олимпиада не найдена.',
        invalidOlympiadTitle: 'Введите название олимпиады.',
    },
    kaz: {
        title: 'Әкімші панелі',
        olympiadTitle: 'Олимпиада атауы',
        createOlympiad: 'Олимпиада құру',
        openOlympiad: 'Тестілеуді басқару',
        registeredCount: 'Тіркелгендер саны',
        registrationStatus: 'Тіркелу',
        subjectName: 'Пән атауы',
        addSubject: 'Пән қосу',
        subjects: 'Пәндер',
        noOlympiads: 'Әзірше олимпиада жоқ.',
        noSubjects: 'Пәндер әлі қосылмаған.',
        assignUser: 'Пайдаланушыны бекіту',
        selectUser: 'Пайдаланушыны таңдаңыз',
        saveUser: 'Сақтау',
        assignedUser: 'Бекітілген',
        noAssignedUser: 'Бекітілмеген',
        noCurators: 'Құрастырушы рөлі бар пайдаланушылар жоқ.',
        olympiadCreated: 'Олимпиада құрылды.',
        subjectCreated: 'Пән қосылды.',
        userAssigned: 'Пайдаланушы пәнге бекітілді.',
        registrationUpdated: 'Тіркелу мәртебесі жаңартылды.',
        archiveOlympiad: 'Архивтеу',
        archiveOlympiadConfirm: 'Олимпиаданы архивтеу керек пе? Ол тізімнен жоғалады.',
        olympiadArchived: 'Олимпиада архивтелді.',
        testingAdmin: 'Тестілеу әкімшілігі',
        backToOlympiads: 'Олимпиадаларға оралу',
        olympiadNotFound: 'Олимпиада табылмады.',
        invalidOlympiadTitle: 'Олимпиада атауын енгізіңіз.',
    },
};
