export const feedbackCopy = {
    rus: {
        title: 'Обратная связь',
        subtitle: 'Отправьте вопрос, замечание или предложение. Ответить на обращение может только администратор.',
        adminSubtitle: 'Просматривайте обращения пользователей и отвечайте на них от имени администратора.',
        newFeedback: 'Новое обращение',
        messageLabel: 'Сообщение',
        messagePlaceholder: 'Опишите проблему, вопрос или предложение.',
        send: 'Отправить',
        emptyMessage: 'Введите текст обращения.',
        feedbackSent: 'Обращение отправлено.',
        history: 'История обращений',
        allRequests: 'Обращения пользователей',
        noFeedbackUser: 'Вы еще не отправляли обращения.',
        noFeedbackAdmin: 'Обращений пока нет.',
        fromUser: 'Пользователь',
        userMessage: 'Сообщение пользователя',
        adminReply: 'Ответ администратора',
        replyPlaceholder: 'Введите ответ пользователю.',
        saveReply: 'Сохранить ответ',
        updateReply: 'Обновить ответ',
        replySaved: 'Ответ сохранен.',
        statusPending: 'Ожидает ответа',
        statusAnswered: 'Есть ответ',
        createdAt: 'Создано',
        answeredAt: 'Ответ дан',
    },
    kaz: {
        title: 'Кері байланыс',
        subtitle: 'Сұрақ, ескерту немесе ұсыныс жіберіңіз. Өтінішке тек әкімші жауап бере алады.',
        adminSubtitle: 'Пайдаланушылардың өтініштерін қарап, әкімші атынан жауап беріңіз.',
        newFeedback: 'Жаңа өтініш',
        messageLabel: 'Хабарлама',
        messagePlaceholder: 'Мәселені, сұрақты немесе ұсынысты сипаттаңыз.',
        send: 'Жіберу',
        emptyMessage: 'Өтініш мәтінін енгізіңіз.',
        feedbackSent: 'Өтініш жіберілді.',
        history: 'Өтініштер тарихы',
        allRequests: 'Пайдаланушылар өтініштері',
        noFeedbackUser: 'Сіз әлі өтініш жібермедіңіз.',
        noFeedbackAdmin: 'Әзірге өтініштер жоқ.',
        fromUser: 'Пайдаланушы',
        userMessage: 'Пайдаланушы хабарламасы',
        adminReply: 'Әкімші жауабы',
        replyPlaceholder: 'Пайдаланушыға жауап енгізіңіз.',
        saveReply: 'Жауапты сақтау',
        updateReply: 'Жауапты жаңарту',
        replySaved: 'Жауап сақталды.',
        statusPending: 'Жауап күтілуде',
        statusAnswered: 'Жауап берілді',
        createdAt: 'Жіберілген уақыты',
        answeredAt: 'Жауап берілген уақыты',
    },
};
